// <auto-generated />
using System;
using CloudYourself.Backend.AppServices.MasterData.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CloudYourself.Backend.AppServices.MasterData.Migrations
{
    [DbContext(typeof(MasterDataDbContext))]
    partial class MasterDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CloudYourself.Backend.AppServices.MasterData.Aggregates.CloudAccount.CloudAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("CloudAccounts");
                });

            modelBuilder.Entity("CloudYourself.Backend.AppServices.MasterData.Aggregates.Tenant.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("CloudYourself.Backend.AppServices.MasterData.Aggregates.CloudAccount.CloudAccount", b =>
                {
                    b.HasOne("CloudYourself.Backend.AppServices.MasterData.Aggregates.Tenant.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.OwnsOne("CloudYourself.Backend.AppServices.MasterData.Aggregates.CloudAccount.CloudAccountBaseData", "BaseData", b1 =>
                        {
                            b1.Property<int>("CloudAccountId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Division")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LegalEntity")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("OperationalContact")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Owner")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CloudAccountId");

                            b1.ToTable("CloudAccounts");

                            b1.WithOwner()
                                .HasForeignKey("CloudAccountId");
                        });

                    b.Navigation("BaseData");
                });

            modelBuilder.Entity("CloudYourself.Backend.AppServices.MasterData.Aggregates.Tenant.Tenant", b =>
                {
                    b.OwnsOne("CloudYourself.Backend.AppServices.MasterData.Aggregates.Tenant.TenantBaseData", "BaseData", b1 =>
                        {
                            b1.Property<int>("TenantId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("BaseData");
                });
#pragma warning restore 612, 618
        }
    }
}
