// <auto-generated />
using CloudYourself.Backend.AppServices.Azure.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CloudYourself.Backend.AppServices.Azure.Migrations
{
    [DbContext(typeof(AzureDbContext))]
    [Migration("20210712124003_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CloudYourself.Backend.AppServices.Azure.Aggregates.Subscription.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CloudAccountId")
                        .HasColumnType("int");

                    b.Property<string>("CreationOperationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("CloudYourself.Backend.AppServices.Azure.Aggregates.Tennant.TenantSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TenantSettings");
                });

            modelBuilder.Entity("CloudYourself.Backend.AppServices.Azure.Aggregates.Subscription.Subscription", b =>
                {
                    b.HasOne("CloudYourself.Backend.AppServices.Azure.Aggregates.Tennant.TenantSettings", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudYourself.Backend.AppServices.Azure.Aggregates.Tennant.TenantSettings", b =>
                {
                    b.OwnsOne("CloudYourself.Backend.AppServices.Azure.Aggregates.Tennant.AppRegistration", "AppRegistration", b1 =>
                        {
                            b1.Property<int>("TenantSettingsId")
                                .HasColumnType("int");

                            b1.Property<string>("AzureAppRegistrationId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AzureAppSecret")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AzureDirectoryTenantId")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TenantSettingsId");

                            b1.ToTable("TenantSettings");

                            b1.WithOwner()
                                .HasForeignKey("TenantSettingsId");
                        });

                    b.OwnsOne("CloudYourself.Backend.AppServices.Azure.Aggregates.Tennant.ManagementTarget", "ManagementTarget", b1 =>
                        {
                            b1.Property<int>("TenantSettingsId")
                                .HasColumnType("int");

                            b1.Property<string>("EnrollmentAccountId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ManagementGroupId")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TenantSettingsId");

                            b1.ToTable("TenantSettings");

                            b1.WithOwner()
                                .HasForeignKey("TenantSettingsId");
                        });

                    b.Navigation("AppRegistration");

                    b.Navigation("ManagementTarget");
                });
#pragma warning restore 612, 618
        }
    }
}
